name: Run Windows 22 Script on Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          # Install PowerShell package manager (required for PowerShellGet module)
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasic) }"

      - name: Check for new release
        run: |
          call run.bat

      - name: Upload Exe Files
        uses: actions/upload-artifact@v2
        with:
          name: Output Files
          path: ./Output
