name: Run Windows Script on Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Date Tag
        id: date_tag
        run: echo "RELEASE_TAG=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const dateTag = process.env.RELEASE_TAG;
            const octokit = context.github;
            const { owner, repo } = context.repo;
            
            const release = await octokit.repos.createRelease({
              owner,
              repo,
              tag_name: dateTag,
              name: `Release ${dateTag}`,
              draft: false,
              prerelease: false
            });
            
            console.log(`Created release with tag: ${dateTag}`);
            console.log(`Release ID: ${release.data.id}`);

      # - name: Install dependencies
      #   run: |
      #     # Install PowerShell package manager (required for PowerShellGet module)
      #     Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      #     iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasic) }"

      - name: Build
        # shell: pwsh
        run: |
          Start-Process -FilePath ".\run.bat" -Wait -NoNewWindow

      - name: Upload Exe Files
        id: upload_files
        uses: actions/upload-artifact@v2
        with:
          name: Output Files
          path: ./Output

      - name: Attach Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.upload_files.outputs.artifact_paths }}
          asset_name: Output Files
          asset_content_type: application/zip
