name: Run Windows 22 Script on Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          # Install PowerShell package manager (required for PowerShellGet module)
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
          iex "& { $(irm https://aka.ms/install-powershell.ps1 -UseBasic) }"

      - name: Check for new release
        shell: pwsh
        run: |
          $owner = "brechtsanders"
          $repo = "winlibs_mingw"

          $latestReleaseUrl = "https://api.github.com/repos/$owner/$repo/releases/latest"
          $latestRelease = Invoke-RestMethod -Uri $latestReleaseUrl
          $latestReleaseDate = [datetime]::Parse($latestRelease.published_at)
          $currentReleaseDate = [datetime]::Now.AddDays(-15)

          if ($latestReleaseDate -gt $currentReleaseDate) {
            Write-Host "New release available: $($latestRelease.tag_name)"
            & ((Split-Path $MyInvocation.InvocationName) + "\Build.ps1") -arch "64" -namePattern "winlibs-x86_64-posix-seh-gcc-[0-9.]+-mingw-w64ucrt-(.*?).7z$"
          }
          else {
            Write-Host "No new release available"
            & "$PSScriptRoot\Build.ps1" -arch "64" -namePattern "winlibs-x86_64-posix-seh-gcc-[0-9.]+-mingw-w64ucrt-(.*?).7z$"
          }

      - name: Upload Exe Files
        uses: actions/upload-artifact@v2
        with:
          name: Output Files
          path: ./Output
