name: Build and Release with Auto Tagging

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Run the build script including auto tagging
      - name: Run build script
        run: |
          cmd /c run.bat

      # Step 3: Create and push the tag
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}

      # Step 4: Debug builds folder
      - name: Debug builds folder
        run: |
          dir builds

      # Step 5: Upload binaries to GitHub Release
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: builds/**/* # Ensure this matches the correct directory
          tag_name: ${{ env.tag }}
          name: Easy MinGW Installer v${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
